blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    
    path('', views.index, name='index'),
    path('add_post', views.add_post, name='add_post'),
]

mysite/urls.py
# from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models


class Post(models.Model):
    def __str__(self):
        return self.title

    title = models.CharField(max_length=256)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

blog/forms.py
from django.forms import ModelForm
from .models import Post


class AddPostForm(ModelForm):
    class Meta(object):
        model = Post
        fields = ["title", "body"]

blog/views.py
import datetime
from django.shortcuts import redirect, render
from django.contrib import messages

from .models import Post
from .forms import AddPostForm



def index(request):
    posts = Post.objects.order_by('-date')
    context = {
        'posts': posts,
    }
    
    return render(request, 'blog.html', context)




def add_post(request):
    if request.method == 'POST':
        form = AddPostForm(request.POST, request.FILES,)
        
        if form.is_valid():
            form.save()
            return redirect('blog:index')
        else:
            messages.error(
                request, f'{form.errors}')
    else:
        form = AddPostForm()
        
    return render(request, 'add_post.html', {'form': form})

blog/templates/add_post.html
{% extends "header.html" %}
{% load crispy_forms_tags %}

{% block content %}
   <div class="container">

    <a href="/admin">Login</a>
    <br>
    <a href="{% url 'blog:index' %}">Home Page</a>
    <br><br>
    

    {% if form.errors %}
        {{form.errors}}
    {% endif %}

        <form method="POST">
        {% csrf_token %}
            {{form|crispy}}
        <button type="submit" class="btn btn-info">Postar</button>
    </form>   
   </div>
{% endblock %}

blog/templates/blog.html
{% extends "header.html" %} 
{% block content %}
  <a href="/admin">Login</a>
  <br />
  <a href="{% url 'blog:add_post' %}">Add new Post</a>
  <br /><br />
  
  {% if posts %} 
    {% for post in posts %}
      <h3>{{ post.title }}</h3>
      <h5>{{ post.date|date:"d-m-Y" }}</h5>
      <p>{{ post.body }}</p>
      <p><--- end of blog.post ---></p>
    {% endfor %} 
  {% endif %} 
{% endblock %}

blog/templates/header.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>My blog site</title>
	<meta charset="utf-8" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	{% load staticfiles %}
</head>

<body class="body" style="background-color:#f6f6f6">
  <br><br>
  <center>
	<h3>My blog</h3>
  </center>
  <br><br>

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  	
  <footer>
    <br> <br> 
  <div class="container">  
    <p>DevSkiller 2018 (c)</p>
  </div>
  </footer>	
</body>

</html>

blog/templates/post.html
{% extends "blog/header.html" %}

{# Your code here #}